# Generated by Django 5.1.6 on 2025-02-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='aaa', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
