# Generated by Django 5.1.6 on 2025-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='components',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='styles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
